/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MediaBinRouteImport } from './routes/media-bin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as DebugUploadRouteImport } from './routes/debug/upload'
import { Route as DebugStatusRouteImport } from './routes/debug/status'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects/$projectId/index'
import { Route as ProjectsProjectIdTimelineRouteImport } from './routes/projects/$projectId/timeline'
import { Route as ProjectsProjectIdExportRouteImport } from './routes/projects/$projectId/export'
import { Route as ProjectsProjectIdBinRouteImport } from './routes/projects/$projectId/bin'

const MediaBinRoute = MediaBinRouteImport.update({
  id: '/media-bin',
  path: '/media-bin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugUploadRoute = DebugUploadRouteImport.update({
  id: '/debug/upload',
  path: '/debug/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugStatusRoute = DebugStatusRouteImport.update({
  id: '/debug/status',
  path: '/debug/status',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdTimelineRoute =
  ProjectsProjectIdTimelineRouteImport.update({
    id: '/timeline',
    path: '/timeline',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdExportRoute = ProjectsProjectIdExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdBinRoute = ProjectsProjectIdBinRouteImport.update({
  id: '/bin',
  path: '/bin',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/media-bin': typeof MediaBinRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/debug/status': typeof DebugStatusRoute
  '/debug/upload': typeof DebugUploadRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId/bin': typeof ProjectsProjectIdBinRoute
  '/projects/$projectId/export': typeof ProjectsProjectIdExportRoute
  '/projects/$projectId/timeline': typeof ProjectsProjectIdTimelineRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/media-bin': typeof MediaBinRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/debug/status': typeof DebugStatusRoute
  '/debug/upload': typeof DebugUploadRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId/bin': typeof ProjectsProjectIdBinRoute
  '/projects/$projectId/export': typeof ProjectsProjectIdExportRoute
  '/projects/$projectId/timeline': typeof ProjectsProjectIdTimelineRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/media-bin': typeof MediaBinRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/debug/status': typeof DebugStatusRoute
  '/debug/upload': typeof DebugUploadRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/bin': typeof ProjectsProjectIdBinRoute
  '/projects/$projectId/export': typeof ProjectsProjectIdExportRoute
  '/projects/$projectId/timeline': typeof ProjectsProjectIdTimelineRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/media-bin'
    | '/auth/login'
    | '/auth/register'
    | '/debug/status'
    | '/debug/upload'
    | '/projects/$projectId'
    | '/projects'
    | '/projects/$projectId/bin'
    | '/projects/$projectId/export'
    | '/projects/$projectId/timeline'
    | '/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/media-bin'
    | '/auth/login'
    | '/auth/register'
    | '/debug/status'
    | '/debug/upload'
    | '/projects'
    | '/projects/$projectId/bin'
    | '/projects/$projectId/export'
    | '/projects/$projectId/timeline'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/media-bin'
    | '/auth/login'
    | '/auth/register'
    | '/debug/status'
    | '/debug/upload'
    | '/projects/$projectId'
    | '/projects/'
    | '/projects/$projectId/bin'
    | '/projects/$projectId/export'
    | '/projects/$projectId/timeline'
    | '/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MediaBinRoute: typeof MediaBinRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  DebugStatusRoute: typeof DebugStatusRoute
  DebugUploadRoute: typeof DebugUploadRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/media-bin': {
      id: '/media-bin'
      path: '/media-bin'
      fullPath: '/media-bin'
      preLoaderRoute: typeof MediaBinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/upload': {
      id: '/debug/upload'
      path: '/debug/upload'
      fullPath: '/debug/upload'
      preLoaderRoute: typeof DebugUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/status': {
      id: '/debug/status'
      path: '/debug/status'
      fullPath: '/debug/status'
      preLoaderRoute: typeof DebugStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/timeline': {
      id: '/projects/$projectId/timeline'
      path: '/timeline'
      fullPath: '/projects/$projectId/timeline'
      preLoaderRoute: typeof ProjectsProjectIdTimelineRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/export': {
      id: '/projects/$projectId/export'
      path: '/export'
      fullPath: '/projects/$projectId/export'
      preLoaderRoute: typeof ProjectsProjectIdExportRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/bin': {
      id: '/projects/$projectId/bin'
      path: '/bin'
      fullPath: '/projects/$projectId/bin'
      preLoaderRoute: typeof ProjectsProjectIdBinRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
  }
}

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdBinRoute: typeof ProjectsProjectIdBinRoute
  ProjectsProjectIdExportRoute: typeof ProjectsProjectIdExportRoute
  ProjectsProjectIdTimelineRoute: typeof ProjectsProjectIdTimelineRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdBinRoute: ProjectsProjectIdBinRoute,
  ProjectsProjectIdExportRoute: ProjectsProjectIdExportRoute,
  ProjectsProjectIdTimelineRoute: ProjectsProjectIdTimelineRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MediaBinRoute: MediaBinRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  DebugStatusRoute: DebugStatusRoute,
  DebugUploadRoute: DebugUploadRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
