[project]
name = "service"
version = "0.1.0"
description = "FastAPI service"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi",
    "sqlmodel>=0.0.31",
    "uvicorn[standard]",
    "email-validator",
    "psycopg2-binary",
    "minio",
    "python-multipart",
    "Pillow",
    "ffmpeg-python",
    "ruff",
    "httpx>=0.28.1",
]

[project.scripts]
start = "service.main:run"
lint = "ruff check ."
format = "ruff format ."

[tool.ruff]
line-length = 120
target-version = "py313"

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "C90", # mccabe complexity
    "B",   # flake8-bugbear
]
ignore = [
    "B008", # Do not perform function call `Depends` in argument defaults
]

[tool.ruff.lint.mccabe]
max-complexity = 10
